@echo OFF
REM automatically generated by make using RULES.ioc.ISIS
set MYDIR=%~dp0
set MYDIRROOT=%MYDIR:~0,-1%
for /F %%I in ( "%MYDIRROOT%" ) do set IOCDIRNAME=%%~nI
set IOCEXE=%IOCDIRNAME:~3%.exe
call %MYDIR%dllPath.bat
%MYDIR%..\..\bin\windows-x64\%IOCEXE% %*
